name: ckan-cloud-operator
channels:
  - defaults
dependencies:
  - python>=3.7
  - psycopg2
  - pip
  - pip:
    - pyyaml<5.3
    - kubernetes
    - click
    - toml
    - dataflows>=0.0.37
    - dataflows-shell>=0.0.8
    - jupyterlab
    - awscli
    - requests<2.22
    - urllib3<1.25
    - httpagentparser
    - ruamel.yaml<1
    - boto3
    - coverage
